### PR TITLE
fix libretro buildbot msvc compile

### PR DESCRIPTION
**Pull request by markwkidd**
Twinaphex contacted me today to say that the XML generator code is causing their MSVC buildbot recipes to fail. Here is an example log with the error: http://p.0bl.net/178416

This PR was written on the run but it's working correctly when compiled for Windows x64 in mysys2 and I wanted to try merging it to find out if it will run through the MSVC buildbot in this form.

### CODE REVIEW

**Comment by grant2258** [comment]
-void print_mame_xml(FILE* out, const struct GameDriver* games[]);
+void print_mame_xml(const struct GameDriver* games[]);

thats causing the error the function takes a file handle

**Comment by grant2258** [comment]
mark tree f42573f  Update info.c look looks like it has the wrong file

**Comment by markwkidd** [comment]
I knew I shouldn't have tried to work on this in the middle of the night.
Oops!

I think everything is building OK now, except it takes the buildbot a while
to work so I still don't know if this fixed microsoft compilation. Finges
crossed.

**Comment by grant2258** [comment]
is this code still valid or is it updated mark ?

**Comment by markwkidd** [comment]
I made an emergency commit after this PR that has the code working again so you'll need to update your source.

Do you mind if I ask what your development environment is like? You probably need to `make clean` then `git pull` then `make -j4`

**Comment by grant2258** [comment]
Im just using make on linux nothing fancy. It's compiling fine. If there is
more problems post updated links to the build errors ill try help out if I
can.

**Comment by markwkidd** [comment]
Thank you, I appreciate it. I think that between the three of us who are
contributing we actually cover a lot of platforms just on our own testing.
Nice.

**Pull request merged**
